swagger: "2.0"
info:
  description: "."
  version: "1.0.0"
  title: "Coronovirus Swagger"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "imranb0104@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/"
tags:
- name: "Coronavirus Stats"
  description: "Statewise and Location wise coronavirus stats"
schemes:
- "https"
- "http"
paths:
  /covid/stats:
    get:
      tags:
      - "Coronavirus Stats"
      summary: "Finds Statewise coronavirus"
      description: "Finds Statewise coronavirus and store this in mongo"
      produces:
      - "application/xml"
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/CovidStats"
        "400":
          description: "Message"
definitions:
  CovidStats:
    type: "object"
    properties:
      Timestamp:
        type: "string"
        format: "int64"
      quantity:
        type: "integer"
        format: "int32"
      shipDate:
        type: "string"
        format: "date-time"
      status:
        type: "string"
        description: "Order Status"
        enum:
        - "placed"
        - "approved"
        - "delivered"
      complete:
        type: "boolean"
        default: false
    xml:
      name: "CovidStats"
  CovidData:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    xml:
      name: "Category"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"